ip:
  121.37.189.240

spring:
  rabbitmq:
    host: ${ip}
    port: 5674
    username: xiaogong
    password: 1225zjzj
    virtual-host: /xk
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000